<a href="https://colab.research.google.com/github/bcury/Python-Projects/blob/main/ML_Deep_Learning_PyTorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(nn.Linear(2,4), nn.Linear(4,1))
x = torch.rand(size=(3,2))
net(x)

tensor([[0.1189],
        [0.0296],
        [0.0046]], grad_fn=<AddmmBackward0>)

In [3]:
print(net[0].state_dict())

OrderedDict([('weight', tensor([[ 0.6751,  0.3159],
        [-0.5004,  0.6720],
        [-0.2798,  0.5969],
        [-0.1338, -0.1294]])), ('bias', tensor([-0.4869, -0.2075, -0.3398, -0.1793]))])


In [4]:
print(net[0].weight.data)

tensor([[ 0.6751,  0.3159],
        [-0.5004,  0.6720],
        [-0.2798,  0.5969],
        [-0.1338, -0.1294]])


In [5]:
print(net[0].bias.data)

tensor([-0.4869, -0.2075, -0.3398, -0.1793])


In [6]:
for name in net.named_parameters():
  print(name)

('0.weight', Parameter containing:
tensor([[ 0.6751,  0.3159],
        [-0.5004,  0.6720],
        [-0.2798,  0.5969],
        [-0.1338, -0.1294]], requires_grad=True))
('0.bias', Parameter containing:
tensor([-0.4869, -0.2075, -0.3398, -0.1793], requires_grad=True))
('1.weight', Parameter containing:
tensor([[ 0.4078,  0.2398, -0.0600, -0.0626]], requires_grad=True))
('1.bias', Parameter containing:
tensor([0.0352], requires_grad=True))


coletando parametros dos blocos

In [7]:
def block1():
  return nn.Sequential(nn.Linear(4,8), nn.ReLU(),
                       nn.Linear(8,4), nn.ReLU())
  
def block2():
  net = nn.Sequential()
  for i in range(2):

    net.add_module(f'block {i}', block1())
  return net

nested_net = nn.Sequential(block2(), nn.Linear(4,1))

In [8]:
print(nested_net)

Sequential(
  (0): Sequential(
    (block 0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)


In [9]:
nested_net[0][1][0].weight.data

tensor([[ 0.2126, -0.0598, -0.2420,  0.0293],
        [-0.2296,  0.2096, -0.4076,  0.0429],
        [-0.3610, -0.3923, -0.1914, -0.4058],
        [-0.2890, -0.0581,  0.4262, -0.3785],
        [-0.4017,  0.1974, -0.4574, -0.0683],
        [-0.2519, -0.1625,  0.0053,  0.4339],
        [-0.2590, -0.2268, -0.4281,  0.4076],
        [-0.1636,  0.2683, -0.1052, -0.2629]])

In [10]:
def init_normal(m):
  if type(m) == nn.Linear:
    nn.init.normal_(m.weight, mean=0, std=0.01)
    nn.init.zeros_(m.bias)

net.apply(init_normal)
net[0].weight.data[0],net[0].bias.data[0]

(tensor([ 0.0257, -0.0065]), tensor(0.))

salavdando e carregando parametros


In [ ]:
import torch
from torch import nn
from torch.nn import functional as F

class MLP(nn.Module):
    def _init_(self):
        super()._init_()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))


net = MLP()
x = torch.randn(size=(2, 20))
y = net(x)

torch.save(net.state_dict(), 'mip.params')

clone = MLP()
clone.load_state_dict(torch.load('mip.params'))

    

pronto carregado e salvado